//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;

namespace LCW.RBAC.Entities
{
    [Serializable]
    public partial class SysGroup : EntityBase
    {
        #region Static Constructor

        /// <summary>
        /// Initializes the <see cref="Account"/> class.
        /// </summary>
        static SysGroup()
        {
        }

        #endregion

        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="Account"/> class.
        /// </summary>
        public SysGroup()
        {
            Initialize();
        }

        protected override void Initialize()
        {
        }

        #endregion

        #region Column Mapped Properties

        private System.Int32 _groupId;

        public virtual System.Int32 GroupId
        {
            get { return _groupId; }
            set
            {
                _groupId = value;
            }
        }

        private System.String _groupName;

        public virtual System.String GroupName
        {
            get { return _groupName; }
            set
            {
                _groupName = value;
            }
        }

        private System.Byte _status;

        public virtual System.Byte Status
        {
            get { return _status; }
            set
            {
                _status = value;
            }
        }

        private System.Int32 _orderBy;

        public virtual System.Int32 OrderBy
        {
            get { return _orderBy; }
            set
            {
                _orderBy = value;
            }
        }

        private System.DateTime _createDate;

        public virtual System.DateTime CreateDate
        {
            get { return _createDate; }
            set
            {
                _createDate = value;
            }
        }

        private System.DateTime _modifiedDate;

        public virtual System.DateTime ModifiedDate
        {
            get { return _modifiedDate; }
            set
            {
                _modifiedDate = value;
            }
        }

        #endregion

        #region Associations Mappings

        private SysGroup _sysGroupMember;

        public virtual SysGroup SysGroupMember
        {
            get { return _sysGroupMember; }
            set
            {
                _sysGroupMember = value;
            }
        }

        private IList<SysGroup> _sysGroupList;

        public virtual IList<SysGroup> SysGroupList
        {
            get { return _sysGroupList; }
            set
            {
                _sysGroupList = value;
            }
        }

        private IList<SysGroupRole> _sysGroupRoleList;

        public virtual IList<SysGroupRole> SysGroupRoleList
        {
            get { return _sysGroupRoleList; }
            set
            {
                _sysGroupRoleList = value;
            }
        }

        private IList<SysUserGroup> _sysUserGroupList;

        public virtual IList<SysUserGroup> SysUserGroupList
        {
            get { return _sysUserGroupList; }
            set
            {
                _sysUserGroupList = value;
            }
        }

        #endregion


        #region Clone

        public virtual SysGroup Clone()
        {
            return (SysGroup)((ICloneable)this).Clone();
        }

        #endregion

        #region Serialization

        /// <summary>
        /// Deserializes an instance of <see cref="Account"/> from XML.
        /// </summary>
        /// <param name="xml">The XML string representing a <see cref="Account"/> instance.</param>
        /// <returns>An instance of <see cref="Account"/> that is deserialized from the XML String.</returns>
        public static SysGroup FromXml(string xml)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(SysGroup));

            using (var sr = new System.IO.StringReader(xml))
            using (var reader = System.Xml.XmlReader.Create(sr))
            {
                return deserializer.ReadObject(reader) as SysGroup;
            }
        }

        /// <summary>
        /// Deserializes an instance of <see cref="Account"/> from a byte array.
        /// </summary>
        /// <param name="buffer">The byte array representing a <see cref="Account"/> instance.</param>
        /// <returns>An instance of <see cref="Account"/> that is deserialized from the byte array.</returns>
        public static SysGroup FromBinary(byte[] buffer)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(SysGroup));

            using (var ms = new System.IO.MemoryStream(buffer))
            using (var reader = System.Xml.XmlDictionaryReader.CreateBinaryReader(ms, System.Xml.XmlDictionaryReaderQuotas.Max))
            {
                return deserializer.ReadObject(reader) as SysGroup;
            }
        }

        #endregion
    }
}


