//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;

namespace LCW.RBAC.Entities
{
    [Serializable]
    public partial class SysPosition : EntityBase
    {
        #region Static Constructor
        
        /// <summary>
        /// Initializes the <see cref="Account"/> class.
        /// </summary>
        static SysPosition()
        {
        }
        
        #endregion

        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="Account"/> class.
        /// </summary>
        public SysPosition()
        {
            Initialize();
        }

        protected override void Initialize()
        {
        }
        
        #endregion
        
        #region Column Mapped Properties
        
        private System.Int32 _positionId;
        
        public virtual System.Int32 PositionId
        {
            get { return _positionId; }
            set
            {
                _positionId = value;
            }
        }
        
        private System.String _positionName;
        
        public virtual System.String PositionName
        {
            get { return _positionName; }
            set
            {
                _positionName = value;
            }
        }
        
        private System.String _positionDescription;
        
        public virtual System.String PositionDescription
        {
            get { return _positionDescription; }
            set
            {
                _positionDescription = value;
            }
        }
        
        private System.Byte _status;
        
        public virtual System.Byte Status
        {
            get { return _status; }
            set
            {
                _status = value;
            }
        }
        
        private System.Int32 _orderBy;
        
        public virtual System.Int32 OrderBy
        {
            get { return _orderBy; }
            set
            {
                _orderBy = value;
            }
        }
        
        private System.DateTime _createDate;
        
        public virtual System.DateTime CreateDate
        {
            get { return _createDate; }
            set
            {
                _createDate = value;
            }
        }
        
        private System.DateTime _modifiedDate;
        
        public virtual System.DateTime ModifiedDate
        {
            get { return _modifiedDate; }
            set
            {
                _modifiedDate = value;
            }
        }
        
        #endregion
        
        #region Associations Mappings
        
        private SysPositionCategory _sysPositionCategory;
        
        public virtual SysPositionCategory SysPositionCategory
        {
            get { return _sysPositionCategory; }
            set
            {
                _sysPositionCategory = value;
            }
        }
        
        private IList<SysUserDetail> _sysUserDetailList;
        
        public virtual IList<SysUserDetail> SysUserDetailList
        {
            get { return _sysUserDetailList; }
            set
            {
                _sysUserDetailList = value;
            }
        }
        
        #endregion
        
        
        #region Clone
        
        public virtual SysPosition Clone()
        {
            return (SysPosition)((ICloneable)this).Clone();
        }
        
        #endregion
        
        #region Serialization
        
        /// <summary>
        /// Deserializes an instance of <see cref="Account"/> from XML.
        /// </summary>
        /// <param name="xml">The XML string representing a <see cref="Account"/> instance.</param>
        /// <returns>An instance of <see cref="Account"/> that is deserialized from the XML String.</returns>
        public static SysPosition FromXml(string xml)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(SysPosition));

            using (var sr = new System.IO.StringReader(xml))
            using (var reader = System.Xml.XmlReader.Create(sr))
            {
                return deserializer.ReadObject(reader) as SysPosition;
            }
        }

        /// <summary>
        /// Deserializes an instance of <see cref="Account"/> from a byte array.
        /// </summary>
        /// <param name="buffer">The byte array representing a <see cref="Account"/> instance.</param>
        /// <returns>An instance of <see cref="Account"/> that is deserialized from the byte array.</returns>
        public static SysPosition FromBinary(byte[] buffer)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(SysPosition));

            using (var ms = new System.IO.MemoryStream(buffer))
            using (var reader = System.Xml.XmlDictionaryReader.CreateBinaryReader(ms, System.Xml.XmlDictionaryReaderQuotas.Max))
            {
                return deserializer.ReadObject(reader) as SysPosition;
            }
        }
        
        #endregion
    }
}


