//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;

namespace LCW.RBAC.Entities
{
    [Serializable]
    public partial class SysRole : EntityBase
    {
        #region Static Constructor
        
        /// <summary>
        /// Initializes the <see cref="Account"/> class.
        /// </summary>
        static SysRole()
        {
        }
        
        #endregion

        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="Account"/> class.
        /// </summary>
        public SysRole()
        {
            Initialize();
        }

        protected override void Initialize()
        {
        }
        
        #endregion
        
        #region Column Mapped Properties
        
        private System.Int32 _roleId;
        
        public virtual System.Int32 RoleId
        {
            get { return _roleId; }
            set
            {
                _roleId = value;
            }
        }
        
        private System.Int32 _parentId;
        
        public virtual System.Int32 ParentId
        {
            get { return _parentId; }
            set
            {
                _parentId = value;
            }
        }
        
        private System.String _roleName;
        
        public virtual System.String RoleName
        {
            get { return _roleName; }
            set
            {
                _roleName = value;
            }
        }
        
        private System.Byte _status;
        
        public virtual System.Byte Status
        {
            get { return _status; }
            set
            {
                _status = value;
            }
        }
        
        private System.DateTime _createDate;
        
        public virtual System.DateTime CreateDate
        {
            get { return _createDate; }
            set
            {
                _createDate = value;
            }
        }
        
        private System.DateTime _modifiedDate;
        
        public virtual System.DateTime ModifiedDate
        {
            get { return _modifiedDate; }
            set
            {
                _modifiedDate = value;
            }
        }
        
        #endregion
        
        #region Associations Mappings
        
        private IList<Authentication> _authenticationList;
        
        public virtual IList<Authentication> AuthenticationList
        {
            get { return _authenticationList; }
            set
            {
                _authenticationList = value;
            }
        }
        
        private IList<SysGroupRole> _sysGroupRoleList;
        
        public virtual IList<SysGroupRole> SysGroupRoleList
        {
            get { return _sysGroupRoleList; }
            set
            {
                _sysGroupRoleList = value;
            }
        }
        
        private IList<SysUserRole> _sysUserRoleList;
        
        public virtual IList<SysUserRole> SysUserRoleList
        {
            get { return _sysUserRoleList; }
            set
            {
                _sysUserRoleList = value;
            }
        }
        
        #endregion
        
        
        #region Clone
        
        public virtual SysRole Clone()
        {
            return (SysRole)((ICloneable)this).Clone();
        }
        
        #endregion
        
        #region Serialization
        
        /// <summary>
        /// Deserializes an instance of <see cref="Account"/> from XML.
        /// </summary>
        /// <param name="xml">The XML string representing a <see cref="Account"/> instance.</param>
        /// <returns>An instance of <see cref="Account"/> that is deserialized from the XML String.</returns>
        public static SysRole FromXml(string xml)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(SysRole));

            using (var sr = new System.IO.StringReader(xml))
            using (var reader = System.Xml.XmlReader.Create(sr))
            {
                return deserializer.ReadObject(reader) as SysRole;
            }
        }

        /// <summary>
        /// Deserializes an instance of <see cref="Account"/> from a byte array.
        /// </summary>
        /// <param name="buffer">The byte array representing a <see cref="Account"/> instance.</param>
        /// <returns>An instance of <see cref="Account"/> that is deserialized from the byte array.</returns>
        public static SysRole FromBinary(byte[] buffer)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(SysRole));

            using (var ms = new System.IO.MemoryStream(buffer))
            using (var reader = System.Xml.XmlDictionaryReader.CreateBinaryReader(ms, System.Xml.XmlDictionaryReaderQuotas.Max))
            {
                return deserializer.ReadObject(reader) as SysRole;
            }
        }
        
        #endregion
    }
}


