//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;

namespace LCW.RBAC.Entities
{
    [Serializable]
    public partial class SysResourceAction : EntityBase
    {
        #region Static Constructor
        
        /// <summary>
        /// Initializes the <see cref="Account"/> class.
        /// </summary>
        static SysResourceAction()
        {
        }
        
        #endregion

        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="Account"/> class.
        /// </summary>
        public SysResourceAction()
        {
            Initialize();
        }

        protected override void Initialize()
        {
        }
        
        #endregion
        
        #region Column Mapped Properties
        
        private System.Int32 _resourceActionId;
        
        public virtual System.Int32 ResourceActionId
        {
            get { return _resourceActionId; }
            set
            {
                _resourceActionId = value;
            }
        }
        
        #endregion
        
        #region Associations Mappings
        
        private SysAction _sysAction;
        
        public virtual SysAction SysAction
        {
            get { return _sysAction; }
            set
            {
                _sysAction = value;
            }
        }
        
        private SysResource _sysResource;
        
        public virtual SysResource SysResource
        {
            get { return _sysResource; }
            set
            {
                _sysResource = value;
            }
        }
        
        private IList<Authentication> _authenticationList;
        
        public virtual IList<Authentication> AuthenticationList
        {
            get { return _authenticationList; }
            set
            {
                _authenticationList = value;
            }
        }
        
        #endregion
        
        
        #region Clone
        
        public virtual SysResourceAction Clone()
        {
            return (SysResourceAction)((ICloneable)this).Clone();
        }
        
        #endregion
        
        #region Serialization
        
        /// <summary>
        /// Deserializes an instance of <see cref="Account"/> from XML.
        /// </summary>
        /// <param name="xml">The XML string representing a <see cref="Account"/> instance.</param>
        /// <returns>An instance of <see cref="Account"/> that is deserialized from the XML String.</returns>
        public static SysResourceAction FromXml(string xml)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(SysResourceAction));

            using (var sr = new System.IO.StringReader(xml))
            using (var reader = System.Xml.XmlReader.Create(sr))
            {
                return deserializer.ReadObject(reader) as SysResourceAction;
            }
        }

        /// <summary>
        /// Deserializes an instance of <see cref="Account"/> from a byte array.
        /// </summary>
        /// <param name="buffer">The byte array representing a <see cref="Account"/> instance.</param>
        /// <returns>An instance of <see cref="Account"/> that is deserialized from the byte array.</returns>
        public static SysResourceAction FromBinary(byte[] buffer)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(SysResourceAction));

            using (var ms = new System.IO.MemoryStream(buffer))
            using (var reader = System.Xml.XmlDictionaryReader.CreateBinaryReader(ms, System.Xml.XmlDictionaryReaderQuotas.Max))
            {
                return deserializer.ReadObject(reader) as SysResourceAction;
            }
        }
        
        #endregion
    }
}


