//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;

namespace LCW.RBAC.Entities
{
    [Serializable]
    public partial class SysResource : EntityBase
    {
        #region Static Constructor
        
        /// <summary>
        /// Initializes the <see cref="Account"/> class.
        /// </summary>
        static SysResource()
        {
        }
        
        #endregion

        #region Default Constructor
        /// <summary>
        /// Initializes a new instance of the <see cref="Account"/> class.
        /// </summary>
        public SysResource()
        {
            Initialize();
        }

        protected override void Initialize()
        {
        }
        
        #endregion
        
        #region Column Mapped Properties
        
        private System.Int32 _resourceId;
        
        public virtual System.Int32 ResourceId
        {
            get { return _resourceId; }
            set
            {
                _resourceId = value;
            }
        }
        
        private System.Int32 _parentId;
        
        public virtual System.Int32 ParentId
        {
            get { return _parentId; }
            set
            {
                _parentId = value;
            }
        }
        
        private System.String _resourceName;
        
        public virtual System.String ResourceName
        {
            get { return _resourceName; }
            set
            {
                _resourceName = value;
            }
        }
        
        private System.String _resourceUrl;
        
        public virtual System.String ResourceUrl
        {
            get { return _resourceUrl; }
            set
            {
                _resourceUrl = value;
            }
        }
        
        private System.Byte _status;
        
        public virtual System.Byte Status
        {
            get { return _status; }
            set
            {
                _status = value;
            }
        }
        
        private System.Int32 _orderBy;
        
        public virtual System.Int32 OrderBy
        {
            get { return _orderBy; }
            set
            {
                _orderBy = value;
            }
        }
        
        private System.DateTime _createDate;
        
        public virtual System.DateTime CreateDate
        {
            get { return _createDate; }
            set
            {
                _createDate = value;
            }
        }
        
        private System.DateTime _modifiedDate;
        
        public virtual System.DateTime ModifiedDate
        {
            get { return _modifiedDate; }
            set
            {
                _modifiedDate = value;
            }
        }
        
        #endregion
        
        #region Associations Mappings
        
        private IList<SysResourceAction> _sysResourceActionList;
        
        public virtual IList<SysResourceAction> SysResourceActionList
        {
            get { return _sysResourceActionList; }
            set
            {
                _sysResourceActionList = value;
            }
        }
        
        #endregion
        
        
        #region Clone
        
        public virtual SysResource Clone()
        {
            return (SysResource)((ICloneable)this).Clone();
        }
        
        #endregion
        
        #region Serialization
        
        /// <summary>
        /// Deserializes an instance of <see cref="Account"/> from XML.
        /// </summary>
        /// <param name="xml">The XML string representing a <see cref="Account"/> instance.</param>
        /// <returns>An instance of <see cref="Account"/> that is deserialized from the XML String.</returns>
        public static SysResource FromXml(string xml)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(SysResource));

            using (var sr = new System.IO.StringReader(xml))
            using (var reader = System.Xml.XmlReader.Create(sr))
            {
                return deserializer.ReadObject(reader) as SysResource;
            }
        }

        /// <summary>
        /// Deserializes an instance of <see cref="Account"/> from a byte array.
        /// </summary>
        /// <param name="buffer">The byte array representing a <see cref="Account"/> instance.</param>
        /// <returns>An instance of <see cref="Account"/> that is deserialized from the byte array.</returns>
        public static SysResource FromBinary(byte[] buffer)
        {
            var deserializer = new System.Runtime.Serialization.DataContractSerializer(typeof(SysResource));

            using (var ms = new System.IO.MemoryStream(buffer))
            using (var reader = System.Xml.XmlDictionaryReader.CreateBinaryReader(ms, System.Xml.XmlDictionaryReaderQuotas.Max))
            {
                return deserializer.ReadObject(reader) as SysResource;
            }
        }
        
        #endregion
    }
}


